### ISSUE TITLE
Spacebar is not detecting

### ISSUE THREAD

**Issue by adhilsalim** [tonalmathew/pressed#1]

**Comment by tonalmathew** [comment]
Hi @adhilsalim thanks for opening the issue, 
The space bar is actually detecting, but it is getting as `" "` from the event listeners. I think we should manually change it.
Are you interested in working with this issue?

**Comment by adhilsalim** [comment]
Sure, let me give it a try.

**Comment by adhilsalim** [comment]
Wow, this code is one of the cleanest I've come across recently! Though I must admit, it was a bit challenging for me to grasp entirely. I hope to improve my coding skills to write code like this in the future. 😇

Thank you so much for giving me the opportunity to fix this issue. I know you could have easily done it in a few seconds.
